# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false

before_cache:
- Rscript -e 'remotes::install_cran(c("rsconnect"))'

deploy:
  provider: script
  script:
  - >-
    Rscript
    -e 'account_info <- lapply(paste0("SHINYAPPS_", c("ACCOUNT", "TOKEN", "SECRET")), Sys.getenv)'
    -e 'do.call(rsconnect::setAccountInfo, account_info)'
    -e 'rsconnect::deployApp(appName = "Covid19")'
  on:
    branch: master
